//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetHatLab.OneNote.TaggingKit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WetHatLab.OneNote.TaggingKit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Add_Tag_26 {
            get {
                object obj = ResourceManager.GetObject("Add_Tag_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Add-in Error.
        /// </summary>
        public static string Addin_ErrorBox_Title {
            get {
                return ResourceManager.GetString("Addin_ErrorBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine OneNote version! Caught exception: {0}.
        /// </summary>
        public static string Adding_ErrorBox_ConnectionError {
            get {
                return ResourceManager.GetString("Adding_ErrorBox_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap copy_26 {
            get {
                object obj = ResourceManager.GetObject("copy_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh_32 {
            get {
                object obj = ResourceManager.GetObject("refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to remove this tag..
        /// </summary>
        public static string RemoveTag_Button_Tooltip {
            get {
                return ResourceManager.GetString("RemoveTag_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; loadImage=&quot;GetImage&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabHome&quot;&gt;
        ///        &lt;group id=&quot;PageTagging&quot; label=&quot;Page Tags&quot; insertAfterMso=&quot;GroupTagging&quot;&gt;
        ///          &lt;button id=&quot;buttonTagPage&quot;
        ///                  label=&quot;Tag and Explore&quot;
        ///                  size=&quot;large&quot;
        ///                  screentip=&quot;Explore Similar Pages and Tag OneNote Pages&quot;
        ///                  onAction=&quot;exploreTags&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ribbon {
            get {
                return ResourceManager.GetString("ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings_32x32 {
            get {
                object obj = ResourceManager.GetObject("settings_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_32x32 {
            get {
                object obj = ResourceManager.GetObject("tag_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TagEditor_ErrorBox_Title {
            get {
                return ResourceManager.GetString("TagEditor_ErrorBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have navigated away form a page with unsaved tag changes.
        ///
        ///Tap or click OK to save changes now.
        ///Tap or click CANCEL to discard the changes.
        /// </summary>
        public static string TagEditor_MessageBox_UnsavedChanges_Message {
            get {
                return ResourceManager.GetString("TagEditor_MessageBox_UnsavedChanges_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Changes.
        /// </summary>
        public static string TagEditor_MessageBox_UnsavedChanges_Title {
            get {
                return ResourceManager.GetString("TagEditor_MessageBox_UnsavedChanges_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag editor dialog failed to open: {0}.
        /// </summary>
        public static string TagEditor_OpenDialogError {
            get {
                return ResourceManager.GetString("TagEditor_OpenDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Notes.
        /// </summary>
        public static string TagEditor_Pages_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagEditor_Pages_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes tagged with one or more tags from the current collection of tags.
        /// </summary>
        public static string TagEditor_Pages_GroupBox_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_Pages_GroupBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags could not be applied to page: {0}.
        /// </summary>
        public static string TagEditor_Save_Error {
            get {
                return ResourceManager.GetString("TagEditor_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to add tag to page.
        /// </summary>
        public static string TagEditor_Tag_AddButton_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_Tag_AddButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or select tag. Press &apos;Enter&apos; to add tag.
        /// </summary>
        public static string TagEditor_Tag_ComboBox_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_Tag_ComboBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to load tags from current page.
        /// </summary>
        public static string TagEditor_Tag_RefreshButton_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_Tag_RefreshButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagEditor_Tags_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagEditor_Tags_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current OneNote page will be tagged with these tags. Add or remove tags as needed..
        /// </summary>
        public static string TagEditor_Tags_GroupBox_ToolTip {
            get {
                return ResourceManager.GetString("TagEditor_Tags_GroupBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Note.
        /// </summary>
        public static string TagEditor_Windows_Title {
            get {
                return ResourceManager.GetString("TagEditor_Windows_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onenotetaggingkit.codeplex.com/.
        /// </summary>
        public static string TaggingKit_About_AddIn_Website {
            get {
                return ResourceManager.GetString("TaggingKit_About_AddIn_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote Tagging Kit.
        /// </summary>
        public static string TaggingKit_About_Appname {
            get {
                return ResourceManager.GetString("TaggingKit_About_Appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2013 WetHat Lab.
        /// </summary>
        public static string TaggingKit_About_Copyright {
            get {
                return ResourceManager.GetString("TaggingKit_About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote Add-In for flexible tagging of OneNote pages.
        /// </summary>
        public static string TaggingKit_About_Description {
            get {
                return ResourceManager.GetString("TaggingKit_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TaggingKit_CancelButton_Text {
            get {
                return ResourceManager.GetString("TaggingKit_CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TaggingKit_SaveButton_Text {
            get {
                return ResourceManager.GetString("TaggingKit_SaveButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TagManager_AboutTab_Header {
            get {
                return ResourceManager.GetString("TagManager_AboutTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Tags.
        /// </summary>
        public static string TagManager_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("TagManager_ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add tag to suggestions.
        /// </summary>
        public static string TagManager_NewTagButton_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_NewTagButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type new tag. Press &apos;Enter&apos; to add..
        /// </summary>
        public static string TagManager_NewTagTextbox_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_NewTagTextbox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Suggestions.
        /// </summary>
        public static string TagManager_TagSuggestionsTab_Header {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestionsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or remove tags used as suggestions in the page tag editor dialog. .
        /// </summary>
        public static string TagManager_TagSuggestionsTab_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestionsTab_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tags.
        /// </summary>
        public static string TagManager_Window_Title {
            get {
                return ResourceManager.GetString("TagManager_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tagSearch_32x32 {
            get {
                object obj = ResourceManager.GetObject("tagSearch_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to clear tag selection.
        /// </summary>
        public static string TagSearch_ClearSelection_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_ClearSelection_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Pages.
        /// </summary>
        public static string TagSearch_Pages_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagSearch_Pages_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages marked with all selected tags .
        /// </summary>
        public static string TagSearch_Pages_GroupBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Pages_GroupBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter query and press enter to start search..
        /// </summary>
        public static string TagSearch_Query_ComboBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Query_ComboBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Notebooks.
        /// </summary>
        public static string TagSearch_Scope_AllNotebooks_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_AllNotebooks_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a scope to look for tagged pages.
        /// </summary>
        public static string TagSearch_Scope_ComboBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Scope_ComboBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Notebook.
        /// </summary>
        public static string TagSearch_Scope_Notebook_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_Notebook_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Section.
        /// </summary>
        public static string TagSearch_Scope_Section_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_Section_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Section Group.
        /// </summary>
        public static string TagSearch_Scope_SectionGroup_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_SectionGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refinement Tags.
        /// </summary>
        public static string TagSearch_Tags_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagSearch_Tags_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tags to filter found pages.
        /// </summary>
        public static string TagSearch_Tags_GroupBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Tags_GroupBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Tagged Pages.
        /// </summary>
        public static string TagSearch_Window_Title {
            get {
                return ResourceManager.GetString("TagSearch_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to show only pages which have this tag..
        /// </summary>
        public static string TagSelector_Tooltip {
            get {
                return ResourceManager.GetString("TagSelector_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to remove this tag..
        /// </summary>
        public static string TagsPanel_RemoveButton_Tooltip {
            get {
                return ResourceManager.GetString("TagsPanel_RemoveButton_Tooltip", resourceCulture);
            }
        }
    }
}
