//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetHatLab.OneNote.TaggingKit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WetHatLab.OneNote.TaggingKit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap copy_26 {
            get {
                object obj = ResourceManager.GetObject("copy_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Links to Pages.
        /// </summary>
        public static string FoundPages_MenuItem_CopyLinks {
            get {
                return ResourceManager.GetString("FoundPages_MenuItem_CopyLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear  Selection.
        /// </summary>
        public static string FoundPages_MenuItem_Deselect_All {
            get {
                return ResourceManager.GetString("FoundPages_MenuItem_Deselect_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string FoundPages_MenuItem_Refresh {
            get {
                return ResourceManager.GetString("FoundPages_MenuItem_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string FoundPages_MenuItem_Select_All {
            get {
                return ResourceManager.GetString("FoundPages_MenuItem_Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refresh_32 {
            get {
                object obj = ResourceManager.GetObject("refresh_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to remove this tag from the list of selected tags..
        /// </summary>
        public static string RemoveTag_Button_Tooltip {
            get {
                return ResourceManager.GetString("RemoveTag_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot; loadImage=&quot;GetImage&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabHome&quot;&gt;
        ///        &lt;group id=&quot;PageTagging&quot; label=&quot;Page Tags&quot; insertAfterMso=&quot;GroupTagging&quot;&gt;
        ///          &lt;button id=&quot;buttonTagPage&quot;
        ///                  label=&quot;Tag Pages&quot;
        ///                  size=&quot;large&quot;
        ///                  screentip=&quot;Add tags to or remove tags from OneNote pages.&quot;
        ///                  onAction=&quot;editTags&quot;
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ribbon {
            get {
                return ResourceManager.GetString("ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings_32x32 {
            get {
                object obj = ResourceManager.GetObject("settings_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or Click to show available actions..
        /// </summary>
        public static string SuggestedTag_Menu_Tooltip {
            get {
                return ResourceManager.GetString("SuggestedTag_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_32x32 {
            get {
                object obj = ResourceManager.GetObject("tag_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to add tags to the selected range of OneNote pages.
        /// </summary>
        public static string TagEditor_AddTags_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_AddTags_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to clear tag selection..
        /// </summary>
        public static string TagEditor_ClearTags_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_ClearTags_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page.
        /// </summary>
        public static string TagEditor_ComboBox_Scope_CurrentNote {
            get {
                return ResourceManager.GetString("TagEditor_ComboBox_Scope_CurrentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Section.
        /// </summary>
        public static string TagEditor_ComboBox_Scope_CurrentSection {
            get {
                return ResourceManager.GetString("TagEditor_ComboBox_Scope_CurrentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Pages.
        /// </summary>
        public static string TagEditor_ComboBox_Scope_SelectedNotes {
            get {
                return ResourceManager.GetString("TagEditor_ComboBox_Scope_SelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of OneNote pages the tags will be applied to..
        /// </summary>
        public static string TagEditor_ComboBox_Scope_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_ComboBox_Scope_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of dialog window failed.
        /// </summary>
        public static string TagEditor_Error_WindowCreation {
            get {
                return ResourceManager.GetString("TagEditor_Error_WindowCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter failed.
        /// </summary>
        public static string TagEditor_Filter_Error {
            get {
                return ResourceManager.GetString("TagEditor_Filter_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to select this tag..
        /// </summary>
        public static string TagEditor_HithighlightedTag_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_HithighlightedTag_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing input failed.
        /// </summary>
        public static string TagEditor_Input_Error {
            get {
                return ResourceManager.GetString("TagEditor_Input_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags have been selected! This operation will not change anything..
        /// </summary>
        public static string TagEditor_NoTagsSelectedWarning {
            get {
                return ResourceManager.GetString("TagEditor_NoTagsSelectedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pages were tagged! Please select a range that contains at least one page and try again..
        /// </summary>
        public static string TagEditor_Popup_NothingTagged {
            get {
                return ResourceManager.GetString("TagEditor_Popup_NothingTagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} page(s) added to the background tagging queue.
        ///
        ///OneNote may be less responsive while tagging is in progress..
        /// </summary>
        public static string TagEditor_Popup_TaggingInProgress {
            get {
                return ResourceManager.GetString("TagEditor_Popup_TaggingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to remove the selected tags from a range of OneNote pages..
        /// </summary>
        public static string TagEditor_RemoveTags_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_RemoveTags_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to replace the tags on a range of OneNote pages with the selected tags..
        /// </summary>
        public static string TagEditor_SetTags_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_SetTags_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Tags.
        /// </summary>
        public static string TagEditor_Suggestions_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagEditor_Suggestions_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags you can add or remove from pages..
        /// </summary>
        public static string TagEditor_Suggestions_GroupBox_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_Suggestions_GroupBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type one or more tags separated by comma &apos;,&apos; and press &apos;Enter&apos;, or select from the list of tags matching the text you typed..
        /// </summary>
        public static string TagEditor_Tag_TextBox_Tooltip {
            get {
                return ResourceManager.GetString("TagEditor_Tag_TextBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagEditor_Tags_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagEditor_Tags_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags to apply to one or more pages..
        /// </summary>
        public static string TagEditor_Tags_GroupBox_ToolTip {
            get {
                return ResourceManager.GetString("TagEditor_Tags_GroupBox_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating page tags failed.
        /// </summary>
        public static string TagEditor_TagUpdate_Error {
            get {
                return ResourceManager.GetString("TagEditor_TagUpdate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TagEditor_WarningMessageBox_Title {
            get {
                return ResourceManager.GetString("TagEditor_WarningMessageBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Pages.
        /// </summary>
        public static string TagEditor_Window_Title {
            get {
                return ResourceManager.GetString("TagEditor_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onenotetaggingkit.codeplex.com/.
        /// </summary>
        public static string TaggingKit_About_AddIn_Website {
            get {
                return ResourceManager.GetString("TaggingKit_About_AddIn_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote Tagging Kit.
        /// </summary>
        public static string TaggingKit_About_Appname {
            get {
                return ResourceManager.GetString("TaggingKit_About_Appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2013 WetHat Lab.
        /// </summary>
        public static string TaggingKit_About_Copyright {
            get {
                return ResourceManager.GetString("TaggingKit_About_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote Add-In for flexible tagging of OneNote pages.
        /// </summary>
        public static string TaggingKit_About_Description {
            get {
                return ResourceManager.GetString("TaggingKit_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Net Framework.
        /// </summary>
        public static string TaggingKit_About_Framework {
            get {
                return ResourceManager.GetString("TaggingKit_About_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfile.
        /// </summary>
        public static string TaggingKit_About_Logfile {
            get {
                return ResourceManager.GetString("TaggingKit_About_Logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string TaggingKit_About_Website {
            get {
                return ResourceManager.GetString("TaggingKit_About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote version lookup failed.
        /// </summary>
        public static string TaggingKit_Error_VersionLookup {
            get {
                return ResourceManager.GetString("TaggingKit_Error_VersionLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}! »{1}«
        ///
        ///Click OK to browse troubleshooting tips and known issues. Click CANCEL to continue.
        ///
        ///If this is a new issue, please consider reporting it. Describe what you were trying to do and attach the add-in log file
        ///»{2}«
        ///
        ///Sorry for the inconvenience!.
        /// </summary>
        public static string TaggingKit_ErrorBox_GenericSevereError {
            get {
                return ResourceManager.GetString("TaggingKit_ErrorBox_GenericSevereError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe {0}  Add-In Error.
        /// </summary>
        public static string TaggingKit_ErrorBox_Title {
            get {
                return ResourceManager.GetString("TaggingKit_ErrorBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://onenotetaggingkit.codeplex.com/wikipage?title={0}.
        /// </summary>
        public static string TaggingKit_Wiki_Page {
            get {
                return ResourceManager.GetString("TaggingKit_Wiki_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to clear tag input..
        /// </summary>
        public static string TagInputBox_ClearInput_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagInputBox_ClearInput_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags found on a range of OneNote pages to the input box.
        /// </summary>
        public static string TagInputBox_Filter_Menu_Tooltip {
            get {
                return ResourceManager.GetString("TagInputBox_Filter_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags from Current Page.
        /// </summary>
        public static string TagInputBox_Filter_MenuItem_CurrentNote {
            get {
                return ResourceManager.GetString("TagInputBox_Filter_MenuItem_CurrentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags from Current Section.
        /// </summary>
        public static string TagInputBox_Filter_MenuItem_CurrentSection {
            get {
                return ResourceManager.GetString("TagInputBox_Filter_MenuItem_CurrentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags from Selected Pages.
        /// </summary>
        public static string TagInputBox_Filter_MenuItem_SelectedNotes {
            get {
                return ResourceManager.GetString("TagInputBox_Filter_MenuItem_SelectedNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a Tag..
        /// </summary>
        public static string TagInputBox_Input_Default {
            get {
                return ResourceManager.GetString("TagInputBox_Input_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags were found in the selected scope!.
        /// </summary>
        public static string TagInputBox_Popup_PresetNoResult {
            get {
                return ResourceManager.GetString("TagInputBox_Popup_PresetNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string TagInputBox_PresetsMenu_Header {
            get {
                return ResourceManager.GetString("TagInputBox_PresetsMenu_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TagManager_AboutTab_Header {
            get {
                return ResourceManager.GetString("TagManager_AboutTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Tags.
        /// </summary>
        public static string TagManager_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("TagManager_ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to show actions for suggested tags.
        /// </summary>
        public static string TagManager_Menu_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to add tag to suggestions.
        /// </summary>
        public static string TagManager_NewTagButton_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_NewTagButton_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type one or more tags separated by &apos;,&apos;. Press &apos;Enter&apos; to add..
        /// </summary>
        public static string TagManager_NewTagTextbox_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_NewTagTextbox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Tag Pages&apos; dialog always on top.
        /// </summary>
        public static string TagManager_PreferencesTab_DialogPreferences_TagEditorOnTop {
            get {
                return ResourceManager.GetString("TagManager_PreferencesTab_DialogPreferences_TagEditorOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, the &apos;Tag Pages&apos; dialog is always on top of all other windows.
        /// </summary>
        public static string TagManager_PreferencesTab_DialogPreferences_TagEditorOnTopTooltip {
            get {
                return ResourceManager.GetString("TagManager_PreferencesTab_DialogPreferences_TagEditorOnTopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Find Tagged Pages&apos; dialog always on top.
        /// </summary>
        public static string TagManager_PreferencesTab_DialogPreferences_TagSearchOnTop {
            get {
                return ResourceManager.GetString("TagManager_PreferencesTab_DialogPreferences_TagSearchOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, the &apos;Find Tagged Pages&apos; dialog is always on top of all other windows.
        /// </summary>
        public static string TagManager_PreferencesTab_DialogPreferences_TagSearchOnTopTooltip {
            get {
                return ResourceManager.GetString("TagManager_PreferencesTab_DialogPreferences_TagSearchOnTopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Preferences.
        /// </summary>
        public static string TagManager_PreferencesTab_DialogPreferencesGroup_Header {
            get {
                return ResourceManager.GetString("TagManager_PreferencesTab_DialogPreferencesGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string TagManager_PreferencesTab_Header {
            get {
                return ResourceManager.GetString("TagManager_PreferencesTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Add-In Appearance and Behavior.
        /// </summary>
        public static string TagManager_PreferencesTab_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_PreferencesTab_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagManager_SuggestedTags_Header {
            get {
                return ResourceManager.GetString("TagManager_SuggestedTags_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TagManager_TagSuggestions_MenuItem_Cancel {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestions_MenuItem_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string TagManager_TagSuggestions_MenuItem_Confirm {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestions_MenuItem_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Tag.
        /// </summary>
        public static string TagManager_TagSuggestions_MenuItem_Delete {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestions_MenuItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this tag from the tag suggestions list and all pages.
        /// </summary>
        public static string TagManager_TagSuggestions_MenuItem_Delete_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestions_MenuItem_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Tag.
        /// </summary>
        public static string TagManager_TagSuggestions_MenuItem_Rename {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestions_MenuItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this tag on the tag suggestions list and on all pages.
        /// </summary>
        public static string TagManager_TagSuggestions_MenuItem_Rename_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestions_MenuItem_Rename_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Tags.
        /// </summary>
        public static string TagManager_TagSuggestionsTab_Header {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestionsTab_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new or remove unused tags available as suggestions in the tag editor. .
        /// </summary>
        public static string TagManager_TagSuggestionsTab_Tooltip {
            get {
                return ResourceManager.GetString("TagManager_TagSuggestionsTab_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Settings.
        /// </summary>
        public static string TagManager_Window_Title {
            get {
                return ResourceManager.GetString("TagManager_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tagSearch_32x32 {
            get {
                object obj = ResourceManager.GetObject("tagSearch_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Check to turn on tag tracking.
        /// </summary>
        public static string TagSearch_CheckBox_Tracking_Text {
            get {
                return ResourceManager.GetString("TagSearch_CheckBox_Tracking_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to clear tag selection.
        /// </summary>
        public static string TagSearch_ClearSelection_Button_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_ClearSelection_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying link to page failed.
        /// </summary>
        public static string TagSearch_Error_CopyLink {
            get {
                return ResourceManager.GetString("TagSearch_Error_CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search failed.
        /// </summary>
        public static string TagSearch_Error_Find {
            get {
                return ResourceManager.GetString("TagSearch_Error_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation to page failed.
        /// </summary>
        public static string TagSearch_Error_PageNavigation {
            get {
                return ResourceManager.GetString("TagSearch_Error_PageNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing search scope failed.
        /// </summary>
        public static string TagSearch_Error_ScopeChange {
            get {
                return ResourceManager.GetString("TagSearch_Error_ScopeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click &apos;❱&apos; to select item.
        ///Tap or click link to navigate to page..
        /// </summary>
        public static string TagSearch_PageItem_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_PageItem_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Pages.
        /// </summary>
        public static string TagSearch_Pages_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagSearch_Pages_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages marked with all selected tags .
        /// </summary>
        public static string TagSearch_Pages_GroupBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Pages_GroupBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to show actions for found pages.
        /// </summary>
        public static string TagSearch_Pages_Menu_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Pages_Menu_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter query and press enter to start search..
        /// </summary>
        public static string TagSearch_Query_ComboBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Query_ComboBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Notebooks.
        /// </summary>
        public static string TagSearch_Scope_AllNotebooks_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_AllNotebooks_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a scope to look for tagged pages.
        /// </summary>
        public static string TagSearch_Scope_ComboBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Scope_ComboBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Notebook.
        /// </summary>
        public static string TagSearch_Scope_Notebook_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_Notebook_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Section.
        /// </summary>
        public static string TagSearch_Scope_Section_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_Section_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Section Group.
        /// </summary>
        public static string TagSearch_Scope_SectionGroup_Label {
            get {
                return ResourceManager.GetString("TagSearch_Scope_SectionGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When tracking is on, tags from the current page are highlighted and the title of the current page is displayed in the status bar. Select one ore more of the highlighted tags to filter for pages related to the current page..
        /// </summary>
        public static string TagSearch_StatusBar_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_StatusBar_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type one or more names separated by comma &apos;,&apos; to locate matching tags in the refinement tags panel.
        /// </summary>
        public static string TagSearch_TagInput_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_TagInput_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refinement Tags.
        /// </summary>
        public static string TagSearch_Tags_GroupBox_Title {
            get {
                return ResourceManager.GetString("TagSearch_Tags_GroupBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more tags to show only pages having these tags..
        /// </summary>
        public static string TagSearch_Tags_GroupBox_Tooltip {
            get {
                return ResourceManager.GetString("TagSearch_Tags_GroupBox_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Tagged Pages.
        /// </summary>
        public static string TagSearch_Window_Title {
            get {
                return ResourceManager.GetString("TagSearch_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag is selected for filtering.
        /// </summary>
        public static string TagSelector_FilterIndicator_Tooltip {
            get {
                return ResourceManager.GetString("TagSelector_FilterIndicator_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} pages tagged with &apos;{2}&apos; match the tag filter.
        /// </summary>
        public static string TagSelector_PageCount_Tooltip {
            get {
                return ResourceManager.GetString("TagSelector_PageCount_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap or click to add or remove this tag from the filter..
        /// </summary>
        public static string TagSelector_Tooltip {
            get {
                return ResourceManager.GetString("TagSelector_Tooltip", resourceCulture);
            }
        }
    }
}
