//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WetHatLab.OneNote.TaggingKit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateRequired {
            get {
                return ((bool)(this["UpdateRequired"]));
            }
            set {
                this["UpdateRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KnownTags {
            get {
                return ((string)(this["KnownTags"]));
            }
            set {
                this["KnownTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 131")]
        public global::System.Drawing.Color PageTagDef_Fontcolor {
            get {
                return ((global::System.Drawing.Color)(this["PageTagDef_Fontcolor"]));
            }
            set {
                this["PageTagDef_Fontcolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PagetagsStyle")]
        public string TagOutlineStyle_Name {
            get {
                return ((string)(this["TagOutlineStyle_Name"]));
            }
            set {
                this["TagOutlineStyle_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Calibri, 9pt, style=Bold")]
        public global::System.Drawing.Font TagOutlineStyle_Font {
            get {
                return ((global::System.Drawing.Font)(this["TagOutlineStyle_Font"]));
            }
            set {
                this["TagOutlineStyle_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double TagEditorWindow_Width {
            get {
                return ((double)(this["TagEditorWindow_Width"]));
            }
            set {
                this["TagEditorWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double TagEditorWindow_Height {
            get {
                return ((double)(this["TagEditorWindow_Height"]));
            }
            set {
                this["TagEditorWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double TagManagerWindow_Width {
            get {
                return ((double)(this["TagManagerWindow_Width"]));
            }
            set {
                this["TagManagerWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double TagManagerWindow_Height {
            get {
                return ((double)(this["TagManagerWindow_Height"]));
            }
            set {
                this["TagManagerWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultScope {
            get {
                return ((int)(this["DefaultScope"]));
            }
            set {
                this["DefaultScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double TagSearchWindow_Width {
            get {
                return ((double)(this["TagSearchWindow_Width"]));
            }
            set {
                this["TagSearchWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double TagSearchWindow_Height {
            get {
                return ((double)(this["TagSearchWindow_Height"]));
            }
            set {
                this["TagSearchWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double TagSearchWindow_Left {
            get {
                return ((double)(this["TagSearchWindow_Left"]));
            }
            set {
                this["TagSearchWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double TagSearchWindow_Top {
            get {
                return ((double)(this["TagSearchWindow_Top"]));
            }
            set {
                this["TagSearchWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchHistory {
            get {
                return ((string)(this["SearchHistory"]));
            }
            set {
                this["SearchHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SearchHistory_Size {
            get {
                return ((int)(this["SearchHistory_Size"]));
            }
            set {
                this["SearchHistory_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double TagEditorWindow_Left {
            get {
                return ((double)(this["TagEditorWindow_Left"]));
            }
            set {
                this["TagEditorWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double TagEditorWindow_Top {
            get {
                return ((double)(this["TagEditorWindow_Top"]));
            }
            set {
                this["TagEditorWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagEditorAlwaysOnTop {
            get {
                return ((bool)(this["TagEditorAlwaysOnTop"]));
            }
            set {
                this["TagEditorAlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagSearchAlwaysOnTop {
            get {
                return ((bool)(this["TagSearchAlwaysOnTop"]));
            }
            set {
                this["TagSearchAlwaysOnTop"] = value;
            }
        }
    }
}
